version: "3.8"

services:
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5672:5672"